version: '3.8'

services:
    db:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: myuser
            POSTGRES_PASSWORD: mypassword
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql  
            - ./queries.sql:/docker-entrypoint-initdb.d/queries.sql 

    
        ports:
          - "5432:5432"
